baseURL = 'https://kestryix.github.io/'
languageCode = 'en-us'
theme = 'archie'
title = 'kestryix'

[params]
	mode="auto"
	useCDN=false
	subtitle = "mini adventures with me"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/kestryix"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/kestryix/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "CTFs"
url = "/ctf"
weight = 2

[[menu.main]]
name = "Sysadmin"
url = "/sysadmin"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5